# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vecdist <- function(a, b) {
    .Call(`_conley_vecdist`, a, b)
}

XeeXhC <- function(M, cutoff, X, e, n1, k, kernel = "bartlett", dist_fn = "haversine") {
    .Call(`_conley_XeeXhC`, M, cutoff, X, e, n1, k, kernel, dist_fn)
}

Bal_XeeXhC <- function(dmat, X, e, n1, k) {
    .Call(`_conley_Bal_XeeXhC`, dmat, X, e, n1, k)
}

XeeXhC_Lg <- function(M, cutoff, X, e, n1, k, kernel, dist_fn) {
    .Call(`_conley_XeeXhC_Lg`, M, cutoff, X, e, n1, k, kernel, dist_fn)
}

TimeDist <- function(times, cutoff, X, e, n1, k) {
    .Call(`_conley_TimeDist`, times, cutoff, X, e, n1, k)
}

DistMat <- function(M, cutoff, kernel = "bartlett", dist_fn = "haversine") {
    .Call(`_conley_DistMat`, M, cutoff, kernel, dist_fn)
}

DistMatPar <- function(mat, cutoff, kernel, dist_fn) {
    .Call(`_conley_DistMatPar`, mat, cutoff, kernel, dist_fn)
}

XeeXhC_Lg_Par <- function(mat, cutoff, X, e, kernel, dist_fn) {
    .Call(`_conley_XeeXhC_Lg_Par`, mat, cutoff, X, e, kernel, dist_fn)
}

Bal_XeeXhC_Par <- function(dmat, X, e) {
    .Call(`_conley_Bal_XeeXhC_Par`, dmat, X, e)
}

XeeXhC_Par <- function(mat, cutoff, X, e, kernel, dist_fn) {
    .Call(`_conley_XeeXhC_Par`, mat, cutoff, X, e, kernel, dist_fn)
}

